Move compiler override to `configure`

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -17,10 +17,13 @@ install_target_lib=
 install_target_include=
 install_target_bin=
 install_target_pkgconfig=
+cc=
 
 HELP_TEXT="
 General-Purpose Flags
 =====================
+--cc COMPILER
+    Override the default compiler.
 -d | --debug
     Compile with debugging information.
 -D name[=value]
@@ -52,6 +55,17 @@ while [ -n "$1" ]; do
   eq_flag_argument=$(echo "$1" | cut -f2 -d=)
 
   case "$flag" in
+    --cc )
+      if [ -n "$eq_flag_argument" ]; then
+        cc=$eq_flag_argument
+      elif [ -n "$2" ]; then
+        cc=$2
+        shift
+      else
+        echo "A path is required for --cc."
+        exit 1
+      fi
+      ;;
     -d | --debug ) debug=1 ;;
     -D )
       if [ -z "$2" ]; then
@@ -106,10 +120,17 @@ else
   echo
 fi
 
+if [ -n "$cc" ]; then
+  compiler_override="CC=$cc"
+else
+  compiler_override=
+fi
+
 echo "Modes"
 echo "-----"
 echo "Debug    : $(int_to_yesno $debug)"
 echo "Unhosted : $(int_to_yesno $unhosted)"
+echo "Compiler override  : $cc"
 echo "Non-fatal warnings : $(int_to_yesno $no_fatal_warnings)"
 echo "Non-fatal test warnings : $(int_to_yesno $no_fatal_test_warnings)"
 echo
@@ -139,6 +160,7 @@ VERSION_FULL=\$(VERSION_MAJOR).\$(VERSION_MINOR).\$(VERSION_PATCH)
 USE_MINIMAL_FLAGS=$minimal_flags
 NO_FATAL_WARNINGS=$no_fatal_warnings
 NO_FATAL_TEST_WARNINGS=$no_fatal_test_warnings
+$compiler_override
 EOF
 
 echo "Done."
